version: '3.7'
services:
  pg:
    image: "postgres:9.6"
    env_file:
      - database.env
    volumes:
      - metrika-pgdata:/var/lib/postgresql/data/
    ports:
      - "5442:5432"

volumes:
  metrika-pgdata:
